name: omega_cliente
description: Cliente Omega - Android, Web e Desktop
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  flutter_animate: ^4.5.2
  drift: ^2.21.0
  sqlite3: ^2.4.0
  path: ^1.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/animacoes/
  generate: true
